Revert "libreoffice 25.2.0"
This reverts commit 08d02cf51d8158f3d2ab095d0820ff1ade6658be.

Attempting to upgrade to this version shows the following error:

```console
$ brew upgrade
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
libreoffice 24.8.4 -> 25.2.0
==> Upgrading libreoffice
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/9792fddc0cd89d50674b764ec32767006c5b4f2a/Casks/l/libreoffice.rb
Already downloaded: /Users/ahedges/Library/Caches/Homebrew/downloads/402743c747d308fd036e27af8570c20a8e6c5a2cb3038423c6ade5c7fd334c85--libreoffice.rb
==> Downloading https://download.documentfoundation.org/libreoffice/stable/25.2.0/mac/aarch64/LibreOffice_25.2.0_MacOS_aarch64.dmg
curl: (56) The requested URL returned error: 403

==> Purging files for version 25.2.0 of Cask libreoffice
Error: libreoffice: Download failed on Cask 'libreoffice' with message: Download failed: https://download.documentfoundation.org/libreoffice/stable/25.2.0/mac/aarch64/LibreOffice_25.2.0_MacOS_aarch64.dmg
```

The download URL[^1] doesn't show this version being available, and the
blog[^2] says, "LibreOffice 25.2 ... is due to arrive next week!", so I
believe this commit was made in error.

[^1]: https://download.documentfoundation.org/libreoffice/stable/
[^2]: https://blog.documentfoundation.org/blog/2025/01/29/libreoffice-project-and-community-recap-january-2025/