Fix breakage of jsl install. (#39793)
Reverting #29176, which breaks install of jsl as follows:

```$ brew cask install jsl
...
==> Downloading http://www.javascriptlint.com/download/jsl-0.3.0-mac.tar.gz
==> Installing Cask jsl
Error: It seems the symlink source '/usr/local/Caskroom/jsl/0.3.0/jsl' is not there.```