Fix Little Flocker hash (#28959)
After the change in #28941 I'm getting a sha256 mismatch. Maybe Little Flocker re-released with the same version number?

```
$ brew update && brew cask install little-flocker >/dev/null
Error: sha256 mismatch
Expected: 3a64a2e287eedb631d374ca5478f10a8379715dca4aa7956d80a8ebf79f2c09f
Actual: 309cb8dfdbdf1ee8a0498a351926629b6128b099b4a20d3ecdca50bb5b71859e
File: /Users/rick/Library/Caches/Homebrew/Cask/little-flocker--1.4.5.dmg
To retry an incomplete download, remove the file above.
```

The "Actual" checksum above does seem correct:

```
$ curl -s https://www.littleflocker.com/downloads/LittleFlocker-1.4.5.dmg | shasum -a 256
309cb8dfdbdf1ee8a0498a351926629b6128b099b4a20d3ecdca50bb5b71859e  -
```